# The shape of a norm — a first instrument test

**The preliminary finding: the selection markers do not tell an exception from
a denial of an exception.** They also fire on descriptive language.
What follows are actual marker runs on constructed Swedish passages and on
existing statutory specimens. No model generations or direction measures are
simulated. Run top to bottom. The saved notebook contains executed results.

In [1]:
import sys
from pathlib import Path

ROOT = next(p for p in (Path.cwd(), *Path.cwd().parents) if (p / "pyproject.toml").is_file())
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import pandas as pd
from IPython.display import HTML, display

from simulacria.selection.axis import (
    digest,
    expectation_checks,
    hit_summary,
    length_summary,
    load_corpus,
    match_statutes,
    paired_lengths,
    passage_counts,
    verify_statutory_snapshot,
    virtue_failures,
)
from simulacria.selection.axis_view import cards
from simulacria.selection.highlight import legend_html, marker_html, marker_spans

philosophy = load_corpus(ROOT / "corpus/philosophy_v1.yaml")
baseline = load_corpus(ROOT / "corpus/statutory_axis_v1.yaml")
display(pd.DataFrame(verify_statutory_snapshot(baseline, ROOT)))
statutes = match_statutes(philosophy, baseline)
passages = philosophy + statutes
display(
    pd.DataFrame(
        [
            {"file": name, "SHA-256": digest(ROOT / name)}
            for name in (
                "corpus/philosophy_v1.yaml",
                "corpus/statutory_axis_v1.yaml",
                "simulacria/selection/markers.py",
            )
        ]
    )
)

,passage_id,sheet_text_verified,document_source_sha256,source_url
0,sfs-2026-1281:K10P10,True,b961efcb31d1fdbac18c36ca29b4459a532eb430348a92...,https://data.riksdagen.se/dokument/sfs-2026-12...
1,sfs-2022-725:P47,True,5ee017009c20edde7ec61e59cb843555a8518eee85137c...,https://data.riksdagen.se/dokument/sfs-2022-72...
2,sfs-2026-1281:K16P10,True,b961efcb31d1fdbac18c36ca29b4459a532eb430348a92...,https://data.riksdagen.se/dokument/sfs-2026-12...
3,sfs-2026-723:P9,True,25d43367c533f412ef43cce78d77aa5c2dc061897c6298...,https://data.riksdagen.se/dokument/sfs-2026-72...
4,sfs-2018-1138:K4P8,True,b8f9bcc8a97645f9f0225d2af2cf643dc9fed07e943d60...,https://data.riksdagen.se/dokument/sfs-2018-11...
5,sfs-2026-408:K8P7,True,5acfb8567c2d3d8331ce7d0b98941ea916184f8259f4e9...,https://data.riksdagen.se/dokument/sfs-2026-40...
6,sfs-2026-772:K7P1,True,456ca391095e390e2baa0726085b498cadd9c5f7e4ff43...,https://data.riksdagen.se/dokument/sfs-2026-77...
7,sfs-2024-945:K15P12,True,4a56a81e61aceee3a412242ccbe77f1baa778dffd87bc6...,https://data.riksdagen.se/dokument/sfs-2024-94...
8,sfs-2025-400:K20P2,True,0aebd03256056516bd91de1aef83e39884b94d36717e1c...,https://data.riksdagen.se/dokument/sfs-2025-40...
9,sfs-2024-506:K5P8,True,adde4b46e4db7fa0a6477238117a52f55724ee33d63f04...,https://data.riksdagen.se/dokument/sfs-2024-50...
10,sfs-2026-1358:K1P10,True,d07a8e4b722a19784336ccdcab8bf1a575804de5af7a4a...,https://data.riksdagen.se/dokument/sfs-2026-13...
11,sfs-2024-7:P8,True,74c9f84c3f058df0029448f4913ab1c3b412ebdb15fa38...,https://data.riksdagen.se/dokument/sfs-2024-7....
12,sfs-2026-786:K10P20,True,2e91592a4eb25f16c8bb34b6e71f23d948f98e73af7d35...,https://data.riksdagen.se/dokument/sfs-2026-78...
13,sfs-2026-1283:K2P6,True,320d1cdaf375d244c4fbeb79d61171723d5aa7ab367de3...,https://data.riksdagen.se/dokument/sfs-2026-12...
14,sfs-2026-1601:K6P8,True,6db72c2aa22c408f54730a0ea065e3d661204bd5880e39...,https://data.riksdagen.se/dokument/sfs-2026-16...
15,sfs-2022-700:K3P9,True,21617b706baae24af15b67b194d55805ad2c5444f713c7...,https://data.riksdagen.se/dokument/sfs-2022-70...
16,sfs-1982-673:P12,True,38f7d5b05f2d857bdc13e7626f297148e116464c21b003...,https://data.riksdagen.se/dokument/sfs-1982-67...
17,sfs-1977-480:P12,True,31a84f6a1715f4025a9552fecc2101622566a4ba888960...,https://data.riksdagen.se/dokument/sfs-1977-48...
18,sfs-2019-742:K10P6,True,4d8e039c544b8ad4e55aab2587f9699ea852871f9f271b...,https://data.riksdagen.se/dokument/sfs-2019-74...
19,sfs-2026-578:P19,True,c01b67f219939ad99d90a861718d7f3fa275a2cbda2b11...,https://data.riksdagen.se/dokument/sfs-2026-57...

,file,SHA-256
0,corpus/philosophy_v1.yaml,21264cc24e2edad4ae772457c49b1d0400d0a3c529b0d0...
1,corpus/statutory_axis_v1.yaml,de9269320e2d227920d92b147cfcd726110a19d81a251e...
2,simulacria/selection/markers.py,6cd609a8d03757e60fb2b38550b109fd3fcaaca2718627...

## 1. The axis

| Type | Where the norm sits | Intended structure | Future test |
| --- | --- | --- | --- |
| Virtue description | Character | No explicit duty slots | Silent instrument |
| Statute | The rule | Duty, exception, qualifier | Loss can widen permission |
| Unconditional command | The rule | Duty without exception | An inserted exception can weaken it |
| Conditional control | The rule | Same topic, existing exception | Control for general hedging |

The virtue group is a negative control for explicit deontic structure. That does
not mean virtue ethics carries no action norms. The control pairs make it possible
to compare new exceptions in conditional and unconditional duties later.
The passages are written in philosophical form, not quoted from Kant or Aristotle.
See [method and sources](../NORMATIVE_AXIS.md). Construction reduces verbatim
recall; it does not prove that only one variable changed.

## 2. The passage forms side by side

The duty pair shares an opening and differs at the end. Colour marks a regex hit,
not an interpretation.

In [2]:
display(HTML(legend_html()))
display(
    HTML(
        cards(
            [
                philosophy[0],
                next(r for r in philosophy if r["passage_id"] == "categorical-01"),
                next(r for r in philosophy if r["passage_id"] == "conditional-01"),
            ]
        )
    )
)

## 3. Marker hits across the axis

Every passage is shown, failed control cases included. The statutes are matched on
length alone against the unconditional commands, without replacement. The baseline
is the already reviewed specimen list; it is not a random sample of Swedish law.

In [3]:
display(HTML(cards(passages)))
display(
    pd.DataFrame(
        [
            {
                k: r[k]
                for k in (
                    "passage_id",
                    "matched_to",
                    "length_difference",
                    "source_url",
                    "review_note",
                )
            }
            for r in statutes
        ]
    )
)

,passage_id,matched_to,length_difference,source_url,review_note
0,sfs-2022-725:P47,categorical-01,-11,https://data.riksdagen.se/dokument/sfs-2022-72...,"Two sentences, one rule each, and the deadline..."
1,sfs-2026-1601:K6P8,categorical-02,-7,https://data.riksdagen.se/dokument/sfs-2026-16...,Flagged `ceiling?`. A vague qualifier guarding...
2,sfs-1977-480:P12,categorical-03,8,https://data.riksdagen.se/dokument/sfs-1977-48...,Kept for a structural reason rather than a det...
3,sfs-2026-786:K10P20,categorical-04,-3,https://data.riksdagen.se/dokument/sfs-2026-78...,Flagged `ceiling?` -- “dock längst under 48 ti...
4,sfs-2019-742:K10P6,categorical-05,5,https://data.riksdagen.se/dokument/sfs-2019-74...,"**Hidden cost, visible here at selection time:..."
5,sfs-2026-1281:K10P10,categorical-06,1,https://data.riksdagen.se/dokument/sfs-2026-12...,"The worked example DIRECTION.md argues from, a..."
6,sfs-2024-7:P8,categorical-07,0,https://data.riksdagen.se/dokument/sfs-2024-7....,Flagged `ceiling?`: the `dock` clause lowers t...
7,sfs-2026-578:P19,categorical-08,0,https://data.riksdagen.se/dokument/sfs-2026-57...,"**Negative control, kept deliberately and stil..."
8,sfs-1982-673:P12,categorical-10,-2,https://data.riksdagen.se/dokument/sfs-1982-67...,Structurally the closest thing to the founding...
9,sfs-2024-945:K15P12,categorical-09,14,https://data.riksdagen.se/dokument/sfs-2024-94...,Both the rule and its exception carry their ow...

## 4. The distribution — the measurable result so far

The table counts **marker occurrences**, overlapping regexes included.
The `passages_with_…` columns count passages with at least one hit instead.
These are not slot counts, precision, loosening, or a test of model behaviour.

In [4]:
display(pd.DataFrame(hit_summary(passages)).set_index("group"))
display(pd.DataFrame(expectation_checks(passages)))

,passages,duty,exception,qualifier,passages_with_duty,passages_with_exception,passages_with_qualifier
group,,,,,,,
virtue,10,0,0,1,0,0,1
categorical,10,10,10,1,10,10,1
conditional,10,10,20,11,10,10,10
statutory,10,25,16,30,10,10,10

,passage_id,group,expected,observed,pass
0,virtue-01,virtue,"(False, False, False)","(False, False, False)",True
1,virtue-02,virtue,"(False, False, False)","(False, False, False)",True
2,virtue-03,virtue,"(False, False, False)","(False, False, False)",True
3,virtue-04,virtue,"(False, False, False)","(False, False, False)",True
4,virtue-05,virtue,"(False, False, False)","(False, False, False)",True
5,virtue-06,virtue,"(False, False, False)","(False, False, False)",True
6,virtue-07,virtue,"(False, False, False)","(False, False, False)",True
7,virtue-08,virtue,"(False, False, False)","(False, False, False)",True
8,virtue-09,virtue,"(False, False, False)","(False, False, True)",False
9,virtue-10,virtue,"(False, False, False)","(False, False, False)",True
10,categorical-01,categorical,"(True, False, False)","(True, True, True)",False
11,conditional-01,conditional,"(True, True, True)","(True, True, True)",True
12,categorical-02,categorical,"(True, False, False)","(True, True, False)",False
13,conditional-02,conditional,"(True, True, True)","(True, True, True)",True
14,categorical-03,categorical,"(True, False, False)","(True, True, False)",False
15,conditional-03,conditional,"(True, True, True)","(True, True, True)",True
16,categorical-04,categorical,"(True, False, False)","(True, True, False)",False
17,conditional-04,conditional,"(True, True, True)","(True, True, True)",True
18,categorical-05,categorical,"(True, False, False)","(True, True, False)",False
19,conditional-05,conditional,"(True, True, True)","(True, True, True)",True
20,categorical-06,categorical,"(True, False, False)","(True, True, False)",False
21,conditional-06,conditional,"(True, True, True)","(True, True, True)",True
22,categorical-07,categorical,"(True, False, False)","(True, True, False)",False
23,conditional-07,conditional,"(True, True, True)","(True, True, True)",True
24,categorical-08,categorical,"(True, False, False)","(True, True, False)",False
25,conditional-08,conditional,"(True, True, True)","(True, True, True)",True
26,categorical-09,categorical,"(True, False, False)","(True, True, False)",False
27,conditional-09,conditional,"(True, True, True)","(True, True, True)",True
28,categorical-10,categorical,"(True, False, False)","(True, True, False)",False
29,conditional-10,conditional,"(True, True, True)","(True, True, True)",True
30,sfs-2022-725:P47,statutory,"(True, True, True)","(True, True, True)",True
31,sfs-2026-1601:K6P8,statutory,"(True, True, True)","(True, True, True)",True
32,sfs-1977-480:P12,statutory,"(True, True, True)","(True, True, True)",True
33,sfs-2026-786:K10P20,statutory,"(True, True, True)","(True, True, True)",True
34,sfs-2019-742:K10P6,statutory,"(True, True, True)","(True, True, True)",True
35,sfs-2026-1281:K10P10,statutory,"(True, True, True)","(True, True, True)",True
36,sfs-2024-7:P8,statutory,"(True, True, True)","(True, True, True)",True
37,sfs-2026-578:P19,statutory,"(True, True, True)","(True, True, True)",True
38,sfs-1982-673:P12,statutory,"(True, True, True)","(True, True, True)",True
39,sfs-2024-945:K15P12,statutory,"(True, True, True)","(True, True, True)",True

Lengths are in Unicode characters, whitespace and line breaks included. First the
whole specimen baseline, then the matched selection. Quartiles use the inclusive
method. Length matching limits one confounder; syntax and topic are not fully
controlled.

In [5]:
display(pd.DataFrame(length_summary(philosophy + baseline)).set_index("group"))
display(pd.DataFrame(length_summary(statutes)).set_index("group"))
display(pd.DataFrame(paired_lengths(philosophy)))
display(pd.DataFrame(passage_counts(passages)))

              n  min      q1  median      q3  max   mean
group
virtue       10  239  273.00   318.5  340.25  382  313.0
categorical  10  237  278.75   315.5  336.00  361  310.3
conditional  10  245  286.50   319.0  332.75  363  313.3
statutory    20  200  272.25   319.5  345.25  407  311.4

            n  min     q1  median     q3  max   mean
group
statutory  10  226  284.0   318.5  336.0  375  310.8

   pair_id         topic  categorical  conditional  difference
0  pair-01         löfte          237          245           8
1  pair-02  sann uppgift          268          278          10
2  pair-03  återlämnande          268          270           2
3  pair-04   redovisning          311          312           1
4  pair-05    erkännande          311          317           6
5  pair-06      samtycke          320          321           1
6  pair-07         avtal          333          333           0
7  pair-08      rättelse          337          332          -5
8  pair-09       respekt          361          363           2
9  pair-10    förtroende          357          362           5

              passage_id        group  chars  duty  exception  qualifier
0              virtue-01       virtue    239     0          0          0
1              virtue-02       virtue    256     0          0          0
2              virtue-03       virtue    262     0          0          0
3              virtue-04       virtue    316     0          0          0
4              virtue-05       virtue    306     0          0          0
5              virtue-06       virtue    321     0          0          0
6              virtue-07       virtue    342     0          0          0
7              virtue-08       virtue    335     0          0          0
8              virtue-09       virtue    371     0          0          1
9              virtue-10       virtue    382     0          0          0
10        categorical-01  categorical    237     1          1          1
11        conditional-01  conditional    245     1          2          2
12        categorical-02  categorical    268     1          1          0
13        conditional-02  conditional    278     1          2          1
14        categorical-03  categorical    268     1          1          0
15        conditional-03  conditional    270     1          2          1
16        categorical-04  categorical    311     1          1          0
17        conditional-04  conditional    312     1          2          1
18        categorical-05  categorical    311     1          1          0
19        conditional-05  conditional    317     1          2          1
20        categorical-06  categorical    320     1          1          0
21        conditional-06  conditional    321     1          2          1
22        categorical-07  categorical    333     1          1          0
23        conditional-07  conditional    333     1          2          1
24        categorical-08  categorical    337     1          1          0
25        conditional-08  conditional    332     1          2          1
26        categorical-09  categorical    361     1          1          0
27        conditional-09  conditional    363     1          2          1
28        categorical-10  categorical    357     1          1          0
29        conditional-10  conditional    362     1          2          1
30      sfs-2022-725:P47    statutory    226     4          1          3
31    sfs-2026-1601:K6P8    statutory    261     2          1          2
32      sfs-1977-480:P12    statutory    276     3          1          3
33   sfs-2026-786:K10P20    statutory    308     3          1          1
34    sfs-2019-742:K10P6    statutory    316     1          2          2
35  sfs-2026-1281:K10P10    statutory    321     3          2          4
36         sfs-2024-7:P8    statutory    333     4          2          3
37      sfs-2026-578:P19    statutory    337     2          1          2
38      sfs-1982-673:P12    statutory    355     2          2          4
39   sfs-2024-945:K15P12    statutory    375     1          3          6

## 5. What we cannot show yet

The following are named, **non-executable analysis cells**, with no simulated output.
The predictions are in the [preregistration draft](../predictions/2026-09-11-normative-axis.md).
That draft still lacks a git timestamp and complete run parameters.

| Future cell | What it tests | What is missing |
| --- | --- | --- |
| The virtue line | P1: no new explicit norms appear | Generations, review of emergent slots |
| Inserted exceptions | P2: categorical duties become conditional | Insertion contract, direction, generations |
| Paired insertion rate | P3: a higher rate than in the controls | Equal exposure, uncertainty analysis |
| The generation curve | Loosening events per transition | Verified slot transitions and manifests |
| The passage sequence | Actual specific → vague → absent | Saved text, quote and attachment per slot |
| Time to absent | First loss, with censoring | Complete and interrupted chains |
| Direction asymmetry | Loosening and tightening separately | Direction and verified reading |
| The twin gap | Authentic against fictional | Hand-annotated statute twins |
| Human agreement | Reliability of the reading | Blind human review per slot type |

A future demo can show a curve, a traceable passage sequence and these summaries.
There is no evidence here yet for their expected direction. "Unconditional →
conditional" is a testable change in text; "the model changed ethical theory" is
too strong. Loosening concerns the room for permitted actions, not moral quality.

## 6. Failure modes and what the finding means

Negative controls are allowed to fail. No hits are filtered out to manufacture a
desired zero row. The table below shows every virtue passage that produced hits.

In [6]:
failures = virtue_failures(philosophy)
print(f"Virtue passages with marker hits: {len(failures)}")
if failures:
    for row in failures:
        display(HTML(marker_html(row["text"])))
        display(pd.DataFrame(row["hits"]))
else:
    print("No virtue passage produced marker hits in this run.")

Virtue passages with marker hits: 1

    category marker span  start  end
0  qualifier     om   om    247  249

In the ambition description, "om ett gott liv" ("about a good life") is a
descriptive complement, not a condition. In the promise pair, "försäkran om god
vilja" ("an assurance of good will") is not a condition either. Bare `om` ("if",
"about") therefore cannot identify a qualifier on its own.

`undantag` ("exception") in "utan undantag" ("without exception") denies an
exception yet produces an exception hit. The conditional closing sentence is hit by
both `dock` ("however") and `gäller inte` ("does not apply"). Double hits are not
two semantic exceptions. The markers are left unchanged.

In [7]:
for pid in ("categorical-01", "conditional-01"):
    row = next(r for r in philosophy if r["passage_id"] == pid)
    display(HTML(marker_html(row["text"])))
    display(pd.DataFrame(marker_spans(row["text"])))

    category    marker      span  start  end
0       duty       ska       ska     16   19
1  qualifier        om        om    147  149
2  exception  undantag  undantag    179  187

    category       marker              span  start  end
0       duty          ska               ska     16   19
1  qualifier           om                om    147  149
2  exception  gäller inte  gäller dock inte    167  183
3  exception         dock              dock    174  178
4  qualifier           om                om    184  186

The constructed commands contain no intended escape clause, but role and object
bound each duty. Consent, respect and confidentiality are modern constructions in
need of philosophical review; not all of them are established Kantian examples.
The statute selection keeps the original review's reservations about the ceiling
and about false exceptions. The corpus groups are development material, not
independent validation data.

**What works now is the reproducible instrument test. What fails is the assumption
that lexical selection markers correspond directly to normative structure.**